# Generated by Django 2.2 on 2020-09-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='shot_zone',
            field=models.CharField(default='unspecified', max_length=200),
        ),
    ]
