# Generated by Django 2.2 on 2020-09-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba', '0002_shot_shot_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='action_type',
            field=models.CharField(default='unspecified', max_length=200),
        ),
    ]
