# Generated by Django 2.2 on 2020-09-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('conference', models.CharField(max_length=200)),
                ('total_games', models.PositiveIntegerField()),
                ('games_won', models.PositiveIntegerField()),
                ('games_lost', models.PositiveIntegerField()),
                ('win_pct', models.FloatField()),
                ('offensive_efficiency', models.FloatField()),
                ('defensive_efficiency', models.FloatField()),
            ],
        ),
    ]
